version: "3.6"

services:
  registry:
    image: registry:2
    restart: always
    networks:
      - net1
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true

  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    networks:
      - net1
    ports:
      - 80:80
    expose:
      - 80
  
networks:
  net1:
    driver: bridge
